/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                            version: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a taste event for the authenticated user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Type of taste event. Catalog lives in docs/02-DATA-SCHEMA.md.
                         * @example correction
                         * @enum {string}
                         */
                        event_type: "photo_analyzed" | "duel_answered" | "correction" | "graph_rebuilt" | "reco_feedback" | "import";
                        /**
                         * @description Event-type-specific payload. See schema doc for shapes.
                         * @example {
                         *       "target": "palette",
                         *       "value": "ocres_poussiereux"
                         *     }
                         */
                        payload: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Event created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            event_type: string;
                            /** Format: date-time */
                            created_at: string;
                        };
                    };
                };
                /** @description No authenticated session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            code: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve a photo row and get a presigned upload URL */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description MIME type the mobile will upload. Whitelist enforced.
                         * @example image/jpeg
                         * @enum {string}
                         */
                        content_type: "image/jpeg" | "image/png" | "image/heic";
                    };
                };
            };
            responses: {
                /** @description Upload URL issued */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            photo_id: string;
                            /** Format: uri */
                            upload_url: string;
                            storage_key: string;
                            expires_in: number;
                            max_bytes: number;
                        };
                    };
                };
                /** @description No authenticated session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            code: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark an upload as complete and enqueue analysis */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Upload verified and queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            photo_id: string;
                            /** @enum {string} */
                            analysis_status: "queued";
                            job_id: string;
                        };
                    };
                };
                /** @description No authenticated session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            code: string;
                        };
                    };
                };
                /** @description Photo not found or not owned by caller */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            code: string;
                        };
                    };
                };
                /** @description Upload missing from storage or exceeded max size (15 MB). Server deletes the oversized object on reject. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            code: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a photo row (for the mobile polling loop on Screen 3) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Photo row */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            user_id: string;
                            storage_key: string;
                            domain: string | null;
                            analysis: {
                                [key: string]: unknown;
                            } | null;
                            /** @enum {string} */
                            analysis_status: "pending" | "queued" | "processing" | "done" | "failed";
                            /** Format: date-time */
                            created_at: string;
                        };
                    };
                };
                /** @description No authenticated session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            code: string;
                        };
                    };
                };
                /** @description Photo not found or not owned by caller */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            code: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
